In [8]:
from kissim.io.dataframe import PocketDataFrame

In [9]:
pocket = PocketDataFrame.from_structure_klifs_id(955)

pocket.ca_atoms

atom.id atom.name  atom.x  atom.y     atom.z  residue.id residue.name
134       135        CA   7.304  15.883  52.160999          40          GLY
138       139        CA   6.560  13.947  49.002998          41          GLU
147       148        CA   3.302  13.736  47.050999          42          LEU
155       156        CA   2.128  10.511  45.270000          43          GLY
159       160        CA   4.827   7.946  44.240002          44          ASP
...       ...       ...     ...     ...        ...         ...          ...
1139     1140        CA   1.706  19.489  33.930000         175          ASP
1147     1148        CA   1.494  20.539  30.247000         176          PHE
1158     1159        CA   3.796  17.730  29.142000         177          GLY
1162     1163        CA   6.548  18.198  31.768999         178          VAL
1169     1170        CA   6.239  14.846  33.610001         179          SER

[85 rows x 7 columns]

In [10]:
ca_atoms = pocket.ca_atoms
for residue_id in pocket._residue_ids:
    ca_atom_coord = ca_atoms[ca_atoms["residue.id"] == residue_id][
        ["atom.x", "atom.y", "atom.z"]
        ].to_numpy()
    print(ca_atom_coord)

[[ 7.304 15.883 52.161]]
[[ 6.56  13.947 49.003]]
[[ 3.302 13.736 47.051]]
[[ 2.128 10.511 45.27 ]]
[[ 4.827  7.946 44.24 ]]
[[ 4.689  7.432 41.28 ]]
[[ 6.857  7.084 38.21 ]]
[[ 6.858 10.36  36.124]]
[[ 9.162 11.323 38.986]]
[[ 9.433 12.733 42.502]]
[[ 6.891 15.48  43.399]]
[[ 7.704 17.409 46.621]]
[[ 5.38  19.293 48.949]]
[[ 3.584 24.426 46.604]]
[[ 4.021 21.22  44.659]]
[[ 7.669 21.114 43.523]]
[[ 9.387 19.063 40.843]]
[[13.201 19.171 40.968]]
[[14.718 18.074 37.623]]
[[13.015 21.863 26.751]]
[[11.191 23.104 29.878]]
[[11.303 26.892 29.171]]
[[ 8.236 26.76  26.886]]
[[ 6.166 25.047 29.658]]
[[ 7.325 27.573 32.32 ]]
[[ 6.568 30.56  30.036]]
[[ 3.078 29.047 29.545]]
[[ 2.385 28.518 33.231]]
[[ 3.667 32.06  33.939]]
[[ 1.576 33.836 31.251]]
[[-1.685 31.896 31.882]]
[[-4.004 33.864 34.156]]
[[-8.754 30.016 37.398]]
[[-8.751 26.429 35.996]]
[[-5.022 26.339 35.174]]
[[-2.324 25.833 37.865]]
[[-0.207 28.878 38.797]]
[[ 3.546 29.046 38.723]]
[[ 4.792 30.24  42.154]]
[[ 8.495 30.103 41.162]]


In [11]:
ca_atoms[["atom.x", "atom.y", "atom.z"]].to_numpy()

array([[  7.304,  15.883,  52.161],
       [  6.56 ,  13.947,  49.003],
       [  3.302,  13.736,  47.051],
       [  2.128,  10.511,  45.27 ],
       [  4.827,   7.946,  44.24 ],
       [  4.689,   7.432,  41.28 ],
       [  6.857,   7.084,  38.21 ],
       [  6.858,  10.36 ,  36.124],
       [  9.162,  11.323,  38.986],
       [  9.433,  12.733,  42.502],
       [  6.891,  15.48 ,  43.399],
       [  7.704,  17.409,  46.621],
       [  5.38 ,  19.293,  48.949],
       [  3.584,  24.426,  46.604],
       [  4.021,  21.22 ,  44.659],
       [  7.669,  21.114,  43.523],
       [  9.387,  19.063,  40.843],
       [ 13.201,  19.171,  40.968],
       [ 14.718,  18.074,  37.623],
       [ 13.015,  21.863,  26.751],
       [ 11.191,  23.104,  29.878],
       [ 11.303,  26.892,  29.171],
       [  8.236,  26.76 ,  26.886],
       [  6.166,  25.047,  29.658],
       [  7.325,  27.573,  32.32 ],
       [  6.568,  30.56 ,  30.036],
       [  3.078,  29.047,  29.545],
       [  2.385,  28.518,  3

In [ ]:
ca_atom_coord = ca_atoms[ca_atoms["residue.id"] == residue_id][
                ["atom.x", "atom.y", "atom.z"]
            ].to_numpy()

In [13]:
type(pocket)

kissim.io.dataframe.PocketDataFrame

In [14]:
ca_atoms[["atom.x", "atom.y", "atom.z"]].to_numpy()

array([[  7.304,  15.883,  52.161],
       [  6.56 ,  13.947,  49.003],
       [  3.302,  13.736,  47.051],
       [  2.128,  10.511,  45.27 ],
       [  4.827,   7.946,  44.24 ],
       [  4.689,   7.432,  41.28 ],
       [  6.857,   7.084,  38.21 ],
       [  6.858,  10.36 ,  36.124],
       [  9.162,  11.323,  38.986],
       [  9.433,  12.733,  42.502],
       [  6.891,  15.48 ,  43.399],
       [  7.704,  17.409,  46.621],
       [  5.38 ,  19.293,  48.949],
       [  3.584,  24.426,  46.604],
       [  4.021,  21.22 ,  44.659],
       [  7.669,  21.114,  43.523],
       [  9.387,  19.063,  40.843],
       [ 13.201,  19.171,  40.968],
       [ 14.718,  18.074,  37.623],
       [ 13.015,  21.863,  26.751],
       [ 11.191,  23.104,  29.878],
       [ 11.303,  26.892,  29.171],
       [  8.236,  26.76 ,  26.886],
       [  6.166,  25.047,  29.658],
       [  7.325,  27.573,  32.32 ],
       [  6.568,  30.56 ,  30.036],
       [  3.078,  29.047,  29.545],
       [  2.385,  28.518,  3